apiVersion: v1
kind: Secret
metadata:
  name: yelp-camp-secrets
type: Opaque
data:
  CLOUDINARY_CLOUD_NAME: ZGU4c2d5eGp5
  CLOUDINARY_KEY: NTYzODQ3MTM5MzQ2NDI5
  CLOUDINARY_SECRET: VEtSTzhRX3k2eWVWZmFjbTNPNmtiTUgyS0gw
  MAPBOX_TOKEN: cGsuZXlKMUlqb2lhMlZsTWpZaUxDSmhJam9pWTIxeFpUSnJlVE0zTVRrNE9ESnljSFZ0YzNjMmNtNTNOQ0o5LmFiRVFEcWYxTGp6eGl4OEdhcXliZlE=
  DB_URL: bW9uZ29kYitzcnY6Ly9rZWU6S2VlQDI2QGNsdXN0ZXIwLmk1djdvNWIubW9uZ29kYi5uZXQvP2FwcE5hbWU9Q2x1c3RlcjA=
